name: Deploy-to-Gandalf-Production

on:
  push:
    branches:
      - release-gandalf

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Nginx - Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: kuclap/server-conf-nginx/kuclap-gandalf-nginx
          registry: docker.pkg.github.com
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./sv1-gandalf/docker/Nginx.Dockerfile
          tags: "1.0.0, latest"
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DO_GANDALF_HOST }}
          username: ${{ secrets.DO_GANDALF_USERNAME }}
          password: ${{ secrets.DO_GANDALF_PASSWORD }}
          port: ${{ secrets.DO_GANDALF_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop kuclap-gandalf-nginx
            docker container prune -f 
            docker image prune -f
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/kuclap/server-conf-nginx/kuclap-gandalf-nginx:latest
            docker run --name kuclap-nginx --network=kuclap --restart=always -v /srv/kuclap.com:/srv/kuclap.com -dit -p 443:443 -p 80:80 docker.pkg.github.com/kuclap/server-conf-nginx/kuclap-gandalf-nginx:latest
